import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TopBar from "@/app/components/topBar";

const larkenMedium = localFont({
  src: "../public/fonts/larken-med.ttf",
  variable: "--font-display",
  display: "swap",
});

export const metadata: Metadata = {
  title: "#1 V6 Improved Wechseljahre - Splittest Optimized",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${larkenMedium.variable} antialiased`}
      >
        <TopBar />
        {children}
      </body>
    </html>
  );
}
